### ISSUE TITLE
Checksum mismatch on installation.

### ISSUE THREAD

**Issue by moritzmhmk** [wearemothership/dicom.ts#25]
When installing the dependencies, `jpeg-lossless-decoder-js` has a mismatch of the checksum. The reported checksum is `sha512-L48KbgTMBa0MDVl0sAkqa528usqKTa4RGntVtQHtymGXGPy8ajhimH1zki8r3NPszW6ChF91BpQIOZ0tQiqSBw==`.

**Comment by nickhingston** [comment]
just done a clean clone - yeah, that's odd - that's new!

the package entry is
```git+https://github.com/rii-mango/JPEGLosslessDecoderJS.git#v2.0.4```

as far as I can tell this is unchanged since 26 Mar 2018

GitHub bug, tar file become corrupt.

**Comment by moritzmhmk** [comment]
By the way, what is the reason for using the git version instead of the one published on [npm](https://www.npmjs.com/package/jpeg-lossless-decoder-js)?

**Comment by nickhingston** [comment]
I think I forked it originally, then put it back...not realising there was an npm module.  So no - will just use that!
