### ISSUE TITLE
configure Renderer to display multiple dcm images at once

### ISSUE THREAD

**Issue by klyanyi** [wearemothership/dicom.ts#71]
hi guys, is it possible to make the Renderer to display multiple dcm images at once? let's say for example there is an array of dcm images and I want to display them all on a single canvas

**Comment by nickhingston** [comment]
My suggestion would be to use 2 canvas's - one off screen one for decoding the image(s).

Then on your visible canvas use:

`yourVisibleCanvas.getContext('2d').drawImage(theRendererCanvas, xOffset, yOffset, outputWidth, outputHeight);`

which is nice and fast.

Any zooming etc would be done on this visible canvas. I personally use paper.js [http://paperjs.org](url) for this purpose.

**Comment by starkey** [comment]
Hi Nick,

thanks, for the suggestion, and yeah that works well for me. I'm stumped on one last thing (and sorry to hijack klyanyi's topic here): 

How do I control greyscale windowing? If I'm reading this correctly, the GreyscaleProgram is created from a copy of a passed IGreyscaleProgram in primeGreyscale(). However, the only user controllable value is knownWindow, which seems to toggle whether to use hard coded values or a LUT.

Obviously I'm missing something here.
