### ISSUE TITLE
Question - How to adjust the window level of DICOM image? 

### ISSUE THREAD

**Issue by whikwon** [wearemothership/dicom.ts#76]
Thank you for sharing your excellent work.
Is there functionality to adjust the window level of DICOM images? Or which code should I modify to add this functionality?

**Comment by nickhingston** [comment]
At this point, the decoder will only use the window given by the image.  We could make this settable reasonably easily, (and then re-decode) but I assume you would like some real time change to the window?

Think this would be a reasonably amount of work to cover all the decoders.

**Comment by whikwon** [comment]
Yes, I'd like to change window level in real time for image viewing purpose. 
I see. Thank you for your response.
