### ISSUE TITLE
Load a dicom image from a device

### ISSUE THREAD

**Issue by AnwarAbdelkabir** [wearemothership/dicom.ts#79]
Hi, 
My question is can we load an image directly from a machine like a scanner or ultrasound which implements DICOM of course without going through local files ?

**Comment by nickhingston** [comment]
you will need to get the data in the browser somehow, so you could fetch the file from a url into a buffer.

**Comment by AnwarAbdelkabir** [comment]
Thank you for the answer, how can i know this url ? is that all machines have a url that allows this ? You have an exemple of javascript code please ?
Thank you.

**Comment by nickhingston** [comment]
This is beyond the scope of this project, it assumes you have access to the file already.

 I assume you are talking to PACS devices, you'll need to look into the communication standards of DICOM and/or specs of the specific device you are connecting to.

closing.
